name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Analyze with SonarCloud

        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        with:
          args: 
            -Dsonar.projectKey=FrancoisMartinez_SOEN343_Avatar
            -Dsonar.organization=francoismartinez
            -Dsonar.sources=backend/src/main,frontend/src
            -Dsonar.tests=backend/src/test,frontend/src/tests
            -Dsonar.exclusions=frontend/src/tests/**
            -Dsonar.java.binaries=backend/target/classes,backend/build/classes
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
          projectBaseDir: .
